---
metadata:
  name: Governify
  short_name: Governify
  description: Governify - A Service agreement management framework
  language: en
  pathPrefix: "/"
  siteImage:
  favicon: "/assets/governify-logo.svg"
  themeColor: "#ff0000"
header:
  enabled: true
  logo: "/assets/governify-logo.svg"
  logoLink: "/"
  helpUrl: ""
  links:
    - text: Home
      link: "/"
      external: false
    - text: Docs
      link: "/about/overview"
      external: false
    - text: Github
      link: https://github.com/governify
      external: true
sidebar:
  enabled: true
  # forcedNavOrder:
  #   - "/introduction"
  #   - "/configuration/basic"
  #   - "/configuration/advanced"
  # expanded:
  groups:
    - order: 1
      path: "/about"
      title: "📘 About"
    - order: 2
      path: "/quickstart"
      title: ":rocket: Quick Start"
    - order: 3
      path: "/customization"
      title: ":wrench: Customization"
    - order: 4
      path: "/development"
      title: "🛠 Development"
    - order: 5
      path: "/components"
      title: "🔗 Components"
    - order: 6
      path: "/reference-guides"
      title: "📑 Reference Guides"
    - order: 7
      path: "/showcases"
      title: "🎞 Showcases"
    - order: 8
      path: "/contributing"
      title: "📣 Contributing"
  links:
    # - text: BooGi
    #   link: https://github.com/filipowm/boogi
    # - text: React
    #   link: https://reactjs.org
  ignoreIndex: true
  # poweredBy:
  #   trademark: "/assets/gatsby.png"
  #   name: Test
  #   link: https://www.gatsbyjs.org
pwa:
  enabled: true
  manifest:
    display: standalone
    crossOrigin: anonymous
    icon: "/assets/favicon.png"

social:
  github: https://github.com/isa-group

features:
  darkMode:
    enabled: true 
    default: false
  editOnRepo:
    location: https://github.com/filipowm/boogi 
    type: github
    editable: false
  mermaid:
    language: "mermaid"
    theme: "dark"
    options:
      themeCSS: ".label foreignObject { font-size: 14px;   overflow: visible; }"
    width: 400
    height: 300
  pageProgress:
    enabled: true
    includePaths:
      - "/configuration/settingup/features"
    excludePaths:
      - "/"
    height: 3
    prependToBody: false
    color: "#A05EB5"
  previousNext:
    enabled: true
    arrowKeyNavigation: true
  propagateNetlifyEnv: true
  rss:
    enabled: true
    title: Governify Docs
    showIcon: false
    copyright: "2020, ISA-GROUP"
    webMaster: "AlexGue"
    managingEditor: "AlexGue"
    categories:
      - Docs as Code
      - GatsbyJS
    ttl: 60
    matchRegex: "^/"
    outputPath: "/rss.xml"
    generator: "boogi"
  scrollTop: true
  search:
    enabled: true
    engine: 'algolia'
    placeholder: 'Search'
    startComponent: 'input' # icon
    excerptSize: 8000
    debounceTime: 380
    snippetLength: 23
    hitsPerPage: 10
    showStats: true
    pagination:
      enabled: true
      totalPages: 10
      showPrevious: true
      showNext: true
  showMetadata: true
  toc:
    show: true
    depth: 4
  fullScreenMode: 
    enabled: false
    hideHeader: true
    hideToc: true
    hideSidebar: true
