name: CD
on:
  push:
    branches:
      - master
      - develop
    tags:
      - 'v*'

jobs:

  deployCommitDraft:
    name: Deploy draft to Netlify
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install # will run `yarn install` command
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: build # will run `yarn build` command
      # ... your other build steps to produce a build directory
      # e.g. `yarn build` for create-react-app

      - uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        with:
          # 5. "gatsby build" creates "public" folder, which is what we are deploying
          args: deploy --dir=public --prod
          secrets: '["NETLIFY_AUTH_TOKEN", "NETLIFY_SITE_ID"]'

  docker:
    name: Build and push Docker images 
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        dockerfile: ['builder', 'runtime', 'develop']
   
    steps:
    - uses: actions/checkout@v2
    
    - name: Build Docker image
      uses: docker/build-push-action@v1.1.0
      with:
        username: isagroup
        password: ${{ secrets.DOCKER_REGISTRY_PASS }}
        repository: isagroup/governify-web
        tags: latest
        tag_with_ref: true
        tag_with_sha: true 
        # Path to the Dockerfile (Default is '{path}/Dockerfile')
        dockerfile: 'docker/Dockerfile.${{ matrix.dockerfile }}'
        always_pull: false
        cache_froms: node:buster-slim
        add_git_labels: true
        push: true # optional, default is true 
